# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches:
      - master
      - "release/*"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      frontend-dir: ./frontend

    strategy:
      matrix:
        node-version: [16.x,18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      working-directory: ${{env.backend-dir}}
      run: npm install
      
    - name: Use Node.js 2 ${{ matrix.node-version }}
      working-directory: ${{env.backend-dir}}
      run: npm build 
      
